config/routes.rb
Rails.application.routes.draw do

get '/login' => 'admin/sessions#new'
get '/logout' => 'admin/sessions#destroy'


  namespace :admin do
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy]
    resources :tags, except: [:index]
  	resources :posts
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :notifications, as: :notifiable, dependent: :destroy
  belongs_to :visitor

  def self.fullname_message params
  	joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :visitor
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
	has_secure_password
	has_many :posts

	validates :fullname, presence: true
	validates :username, presence: true, format: {with: /@/, message: 'is not valid username'}
	validates :password , presence: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :moderator
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  

  def self.matching_title_or_content search
  	where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  has_many :tags, through: :post_tags
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :posts, through: :post_tags
	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)		
	end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
	has_many :notification, as: :notifiable, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :messages, dependent: :destroy
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def index
  	if params[:search].present?
  		@comments = Comment.fullname_message(params[:search]).page(params[:page]).per(3)
  	else
  		@comments = Comment.where(status: to_bool(params[:status])).page params[:page]

  	end
  end

  def update
  	@comment = Comment.find(params[:id])
  	if @comment.update(status: params[:status])
  		redirect_to :back, notice: 'Comment updated successfully'
  	else
  		redirect_to :back, notice: 'There was a problem in updating comment'
  	end
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to :back, notice: "Comment deleted succesfully"
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < Admin::ApplicationController
  def index
  	@messages = Message.all.order(id: :desc).page(params[:page]).per(10)
  end

  def show
  end

  def update
  end

  def destroy
  	@message = Message.find(params[:id])
  	@message.destroy

  	redirect_to :back, notice: "Message deleted successfully"
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def index
    if params[:search].present?
      @posts = Post.matching_title_or_content(params[:search]).page(params[:page])
    else
      @posts = Post.all.order(id: :desc).page(params[:page]).per(10)
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.moderator_id = current_moderator.id
    
    if @post.save
      redirect_to admin_posts_path, notice: "Post was successfully created"
    else
      flash[:alert] = "There was a problem in creating post"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_path, notice: "Post was successfully updated"
    else
      flash[:alert] = "There was a problem in updating post"
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to :back, notice: "Post was successfully deleted"
  end

  private

  def post_params
    params.require(:post).permit(:id, :title, :content, :publish, tag_ids: [])
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
	before_action :authorize, except: [:new, :create, :destroy]
  def new
  end

  def create
  	@moderator = Moderator.find_by(username: params[:username]).try(:authenticate, params[:password])
  	if @moderator
  		session[:current_moderator_id] = @moderator.id
  		redirect_to admin_moderators_url, notice: "You have successfully signed in"
  	else
  		flash[:alert] = 'There was a problem with username or password'
  		render :new
  	end
  end

  def destroy
  	session[:current_moderator_id] = nil
  	redirect_to '/login', notice: "You have successfully logged out"
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def new
    @tag = Tag.new
    @tags = Tag.all.order(id: :desc)
  end

  def create
    tags_params[:name].split(',').map do |n|
      Tag.new(name: n).save
    end
    redirect_to new_admin_tag_url, notice: 'Tag is successfully created'
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update tags_params
      redirect_to new_admin_tag_url, notice: "Tag is successfully updated."
    else
      flash[:alert] = "There is problem in updating tag."
      render :edit
    end
  end

  def show
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to :back, notice: 'Tag successfully deleted'
  end

  private

  def tags_params
    params.require(:tag).permit(:id, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
	def status_converter(status,truthy: 'Active', falsey: 'Pending')
		if status
			truthy
		else
			falsey
		end
	end
	def time_ago time
		"#{time_ago_in_words(time)} ago"
	end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper

	def create_delete_button tag
		if tag.in_use?
			link_to '#' do
				content_tag(:button, 'Delete',class: 'disabled')
			end
		else
			link_to admin_tag_url(tag), method: :delete, data: { confirm: 'Are you sure'} do
				content_tag(:button, 'Delete')
			end
		end	
	end
end

app/helpers/admin/visitors_helper.rb
module Admin::VisitorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/comments/index.html.erb
<h1>Comments</h1>


<p>
	<%= render 'search', route: admin_comments_path %>
</p>

<p>
	<%= link_to 'Approved', admin_comments_path(status: true) %>
	<%= link_to 'Un-approved', admin_comments_path(status: false) %>
</p>

<% @comments.each do |comment| %>
	<p><b><%= comment.visitor.fullname %></b> Posted message on <b><%= comment.post.title %></b></p>
	<p><%= comment.message %></p>
	<p><%= link_to 'Delete', admin_comment_path(comment), method: :delete, data: {confirm: 'Are you sure'} %>
	<%= 
		if params[:status] == 'true'
			link_to 'Un-approve', admin_comment_path(comment, status: false), method: :put
		else
			link_to 'Aapprove', admin_comment_path(comment, status: true), method: :put
		end
	%>
		</p>
	<hr>
<% end %>

<%= paginate @comments %>

app/views/admin/messages/index.html.erb
<h1>Messages</h1>
<% @messages.each do |message| %>
	<p>
		<%= message.visitor.fullname %><br>
		<%= truncate(message.content, lenght: 60, seperator: '') %><br>
		<%= status_converter(message.status,truthy: 'Read', falsey: 'Not-Read') %><br>
		<%= time_ago(message.created_at) %><br>
		<%= link_to 'Delete', admin_message_path(message), method: :delete, data: {confirm: 'Are you sure?'} %>
	</p>
<% end %>

<%= paginate @messages %>

app/views/admin/messages/show.html.erb
<h1>Admin::Messages#show</h1>
<p>Find me in app/views/admin/messages/show.html.erb</p>

app/views/admin/posts/_form.html.erb
<p><%= render 'validation_errors', object: @post %></p>

<%= form_for [:admin, @post] do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content %>
		<%= f.text_field :content %>
	</p>
	<p>
		<%= f.label :publish %>
		<%= f.check_box :publish %>
	</p>
	<p>
		<%= f.select :tag_ids, Tag.all.collect {|t| [t.name, t.id]}, {prompt: 'Select Tag'}, multiple: :true %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>
<%= render 'form' %>

app/views/admin/posts/index.html.erb
<h1>Admin::Posts#index</h1>
<p><%= link_to 'New Post', new_admin_post_path %></p>

<p>
	<%= render 'search', route: admin_posts_path %>
</p>

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Title</th>
			<th>Publish</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td><%= truncate(post.title, length: 60, separate: '') %></td>
				<td><%= status_converter(post.publish,truthy: 'Active', falsey: 'Pending') %></td>
				<td>
					<%= link_to 'Edit',edit_admin_post_path(post) %> |
					<%= link_to 'Show',admin_post_path(post) %> |
					<%= link_to 'Delete', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure'} %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<p><%= paginate @posts %></p>

app/views/admin/posts/new.html.erb
<h1>Admin::Posts#new</h1>
<%= render 'form' %>

app/views/admin/posts/show.html.erb
<h1>Admin::Posts#show</h1>
<p><b>Title:</b> <%= @post.title %></p>
<p><b>Content:</b> <%= @post.content %></p>
<p><b>Publish:</b> <%= status_converter(@post.publish) %></p>
<p><b>Created:</b> <%= time_ago(@post.created_at) %></p>

app/views/admin/tags/edit.html.erb
<h1>Admin::Tags#edit</h1>

<%= form_for [:admin, @tag] do |f| %>
	<p><%= f.label :name %></p>
	<p><%= f.text_field :name %></p>
	<p><%= f.submit %></p>
<% end %>

app/views/admin/tags/new.html.erb
<h1>Admin::Tags#new</h1>


<%= form_for [:admin, @tag] do |f| %>
	<p><%= f.text_area :name, placeholder: 'eg Ruby, python, Php' %></p>
	<p><%= f.submit %></p>
<% end %>

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Name</th>
			<th>Status</th>
			<th>Created</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @tags.each do |tag| %>
			<tr>
				<td><%= tag.name %></td>
				<td><%= status_converter(tag.in_use?,truthy: 'In use', falsey: 'Not in use') %></td>
				<td><%= time_ago tag.created_at %></td>
				<td>
					<%= link_to edit_admin_tag_url(tag) do %>
						<button type="button">Edit</button>
					<% end %>
					<%= create_delete_button tag %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/tags/show.html.erb
<h1>Admin::Tags#show</h1>
<p>Find me in app/views/admin/tags/show.html.erb</p>